name: flutter_horizontal_calendar
description: Flutter UI package to interact with canelder in horizontal view. This package also supports custom header and chile element.
version: 0.0.1
homepage: https://github.com/pratikbaid3/flutter_horizontal_calendar

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.horizontal_calendar
        pluginClass: HorizontalCalendarPlugin
      ios:
        pluginClass: HorizontalCalendarPlugin
      linux:
        pluginClass: HorizontalCalendarPlugin
      macos:
        pluginClass: HorizontalCalendarPlugin
      windows:
        pluginClass: HorizontalCalendarPluginCApi
      web:
        pluginClass: HorizontalCalendarWeb
        fileName: horizontal_calendar_web.dart
